universe = vanilla
Executable = condor_runscript_TT_NoJEC.sh
Output = condor/log-$(ClusterId).$(ProcId).out
Error  = condor/log-$(ClusterId).$(ProcId).err
Log    = condor/log-$(ClusterId).$(ProcId).log

arguments    = $(ClusterId) $(ProcId) $(INFILE)

Notification = never
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)


queue INFILE from filelists2017/inputs_TT/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8.txt

queue INFILE from filelists2017/inputs_TT/DoubleEG.txt

queue INFILE from filelists2017/inputs_TT/DoubleMuon.txt

queue INFILE from filelists2017/inputs_TT/ST_s-channel_4f_leptonDecays_TuneCP5_PSweights_13TeV-amcatnlo-pythia8.txt

queue INFILE from filelists2017/inputs_TT/ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8.txt

queue INFILE from filelists2017/inputs_TT/ST_t-channel_top_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8.txt

queue INFILE from filelists2017/inputs_TT/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.txt

queue INFILE from filelists2017/inputs_TT/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8.txt

queue INFILE from filelists2017/inputs_TT/MuonEG.txt

queue INFILE from filelists2017/inputs_TT/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.txt

queue INFILE from filelists2017/inputs_TT/TTToHadronic_TuneCP5_PSweights_13TeV-powheg-pythia8.txt

queue INFILE from filelists2017/inputs_TT/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt

queue INFILE from filelists2017/inputs_TT/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8.txt

queue INFILE from filelists2017/inputs_TT/WW_TuneCP5_13TeV-pythia8.txt

queue INFILE from filelists2017/inputs_TT/WZ_TuneCP5_13TeV-pythia8.txt

queue INFILE from filelists2017/inputs_TT/ZZ_TuneCP5_13TeV-pythia8.txt

queue INFILE from filelists2017/inputs_TT/DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8.txt
